### ISSUE TITLE
It seems a bug

### ISSUE THREAD

**Issue by chikara-chan** [aribouius/asset-require-hook#1]
![image](https://cloud.githubusercontent.com/assets/13572030/23643988/f19e9e5a-033f-11e7-8198-237a2a2f0dc2.png)

It happens when the image exceed the base64 limit. 
The server side `asset-require-hook` render a url started without '/'
The client side `file-loader` render a url started with '/'

**Comment by chikara-chan** [comment]
Now, we have to specify {name: '/[hash].[ext]'}

However, it should be added prefix '/' for default.

**Comment by lewisloofis** [comment]
have the same error here, also if you use '/' in front of the name value, the result will be different hash in client and server code. I'm building server side rendering application and get confused by this

**Comment by aribouius** [comment]
@chikara-chan @lewisloofis the reason you are getting the react checksum error is because `file-loader` by default [prepends your configured webpack `publicPath`](https://github.com/webpack-contrib/file-loader/blob/master/index.js#L63) to the image name/hash.

Like you noted, a way around this is to do something like `{ name: '/[hash].[ext]' }`.  The reason we can't add it by default is that this plugin can't infer what your webpack configuration looks like.

Since this plugin attempts to support the same configuration options as `file-loader` and `url-loader`, I have added support for a `publicPath` option...
```javascript
require('asset-require-hook')({
  extensions: ['jpg'],
  name: '[hash].[ext]',
  publicPath: '/'
})
```
